services:
#  java:
#    image: openjdk:11
#    ports:
#      - 9090:9090
#    volumes:
#      - ./:/app
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
